
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvlsbsfaysulrerikoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dmxzYnNmYXlzdWxyZXJpa295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDAyNjQsImV4cCI6MjA1OTc3NjI2NH0.8EMzXhnbG4HcwblD5nUqruBMn8ABEsT84QxAiDsCVJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Types personnalisés pour un usage plus facile
export type VehicleType = {
  id: string;
  name: string;
  driver_id: string;
  is_default?: boolean;
  icon?: string;
  created_at: string;
  updated_at: string;
};
