// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddjsodptyspichsopyqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkanNvZHB0eXNwaWNoc29weXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDg4MjUsImV4cCI6MjA2MDEyNDgyNX0.L8XBYSJir1bg2exuf4XtaOSVO4GV1aaggAnzFWhLyZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);